name: Deploy Application to DEV
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Assure-toi que c'est la version compatible avec ton projet

      - name: Install dependencies
        run: |
          yarn

      - name: Build libraries and application
        run: |
          node scripts/build.js
          yarn run build

      - name: List files in dist
        run: ls -la dist
      - name: Upload dist folder to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.0.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21 # Tu peux ajuster cela si ton serveur FTP utilise un autre port
          local-dir: dist/doc-builder-front/ # Le chemin du dossier généré par la commande npm run build
          server-dir: /front/dev/ # Le répertoire distant où tu veux envoyer ton application

      - name: Notify success
        run: echo "Déploiement effectué avec succès sur le serveur FTP !"
